typer_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  ears: realtime-stt
  brain: deepseek-v3 # deepseek-v3, gemini-pro, mistral:instruct
  voice: elevenlabs # local, elevenlabs
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K
base_assistant:
  assistant_name: Ada
  human_companion_name: Dan
  ears: realtime-stt
  brain: ollama:phi4 # deepseek-v3, ollama:phi4, ollama:<any installed model>
  elevenlabs_voice: WejK3H1m7MI9CHnIjW9K